version: "3.9"

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  # Node API service
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      Mongo_URL: mongodb://mongo_db:27017/vehicledb
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
